### ISSUE TITLE
U-Net Example

### ISSUE THREAD

**Issue by kmader** [Calysto/conx-notebooks#1]
A u-net example notebook would be great for demonstrating the training. I have already done a simple keras-based example for my lecture (http://nbviewer.jupyter.org/github/kmader/Quantitative-Big-Imaging-2018/blob/d956f1c644ab249c333c535bdbbfcd614a769324/Lectures/05-SupervisedApproaches.ipynb#U-Net) but the conx interface seems much better suited for teaching

**Comment by kmader** [comment]
something along the lines of this notebook using EM data: https://www.kaggle.com/kmader/visualizing-u-net-with-conx/

**Comment by dsblank** [comment]
Thanks for idea, and for sharing! (Sorry I didn't see this until now; was on vacation).

Very nice demonstrations. How did you get conx installed on a kaggle image? 

One correction: conx is actually a team effort with colleagues, and great input from people like you :)

**Comment by kmader** [comment]
Conx is a great repository for teaching, it makes tweaking and visualizing networks much easier.  as for installing in kaggle, the recently added the feature so you can go to settings and pip install packages from pypi or directly from github, so you can just add Calysto/conx, unfortunately the widgets only work when you are running the notebook, not once it has been compiled / submitted

**Comment by dsblank** [comment]
Thanks for the info on kaggle. If you have suggestions for making conx better in the classroom, please let us know, or feel free to make PRs. 

Could we point to your conx notebooks as examples?

**Comment by dsblank** [comment]
I don't see how to mix Jupyter notebooks with "settings" so that I can add conx as a pip requirement. Any ideas?

**Comment by kmader** [comment]
If you go settings when 'running' the kernel on kaggle you can specify the packages to install
![image](https://user-images.githubusercontent.com/116120/38251659-63eb91b0-3752-11e8-9677-337ad9b62566.png)

Feel free to point to the link, I am working on a self-contained dataset to maybe PR into conx-notebooks

**Comment by dsblank** [comment]
Ah, thank you for the picture... (hidden behind << arrow)... found it. I had requested that conx be added to the default image a month ago, but no word yet:

https://github.com/Kaggle/docker-python/pull/191/

**Comment by dsblank** [comment]
Do you know if pressing the "arrow cycle" button is the only way to "restart interactive session"?

![screenshot from 2018-04-03 09-41-48](https://user-images.githubusercontent.com/168568/38254010-1c373468-3726-11e8-96d9-00bbdd8c160c.png)

**Comment by kmader** [comment]
As far as I know it is, I assume Kaggle (maybe @nerdcha) is working to make adding packages and restarting kernels a bit more seamless.

**Comment by kmader** [comment]
And a more fun example on the data sciencebowl data: https://www.kaggle.com/kmader/dsb2018-visualizing-u-net-with-conx
